package com.jsu.bean.bak;

public class Card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.id
     *
     * @mbg.generated Tue Apr 07 17:26:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card
     *
     * @mbg.generated Tue Apr 07 17:26:29 CST 2020
     */
    private String card;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.id
     *
     * @return the value of card.id
     *
     * @mbg.generated Tue Apr 07 17:26:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.id
     *
     * @param id the value for card.id
     *
     * @mbg.generated Tue Apr 07 17:26:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card
     *
     * @return the value of card.card
     *
     * @mbg.generated Tue Apr 07 17:26:29 CST 2020
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card
     *
     * @param card the value for card.card
     *
     * @mbg.generated Tue Apr 07 17:26:29 CST 2020
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }
}